language: python
matrix:
    include:
        - python: "3.8"
        env: TOXENV=py38
        - python: "3.8"
        env: TOXENV=lint
install:
    - pip install -U pip setuptools tox
script:
    - tox
