language: python
matrix:
    include:
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.9"
          env: TOXENV=py39
        - python: "3.9"
          env: TOXENV=lint
install:
    - pip install -U pip setuptools tox
script:
    - tox
